=== mmbalbas1132/anexos_temario/tema11/ejemplos tema/coches.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:import namespace="http://www.w3.org/2001/XMLSchema-instance" schemaLocation="xsi.xsd"/>
    <xs:element name="concesionario">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="coche"/>
            </xs:sequence>
            <xs:attribute name="provincia" use="required" type="xs:NCName"/>
            <xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="coche">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="marca"/>
                <xs:element ref="modelo"/>
                <xs:element ref="cv"/>
                <xs:element ref="combustible"/>
                <xs:element ref="precio"/>
                <xs:element ref="año"/>
                <xs:element ref="interesado"/>
                <xs:element ref="fecha_limite"/>
            </xs:sequence>
            <xs:attribute name="matricula" use="required" type="xs:NMTOKEN"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="marca" type="xs:NCName"/>
    <xs:element name="modelo" type="xs:NCName"/>
    <xs:element name="cv" type="xs:integer"/>
    <xs:element name="combustible" type="xs:NCName"/>
    <xs:element name="precio" type="xs:integer"/>
    <xs:element name="año" type="xs:integer"/>
    <xs:element name="interesado" type="xs:string"/>
    <xs:element name="fecha_limite" type="xs:string"/>
</xs:schema>

=== mmbalbas1132/anexos_temario/tema11/ejemplos tema/coches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<concesionario>-->
<!--    <coche matricula="6732KPC">-->
<!--        <marca>Seat Ateca</marca>-->
<!--        <combustible>Gasolina</combustible>-->
<!--        <precio>23000</precio>-->
<!--    </coche>-->
<!--    <coche matricula="8280KWT">-->
<!--        <marca>Volkswagen Golf</marca>-->
<!--        <combustible>Diesel</combustible>-->
<!--        <precio>25000</precio>-->
<!--    </coche>-->
<!--</concesionario>-->

<concesionario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="coches.xsd"
provincia="Madrid">
    <coche matricula="6732KPC">
        <marca>Seat</marca>
        <modelo>Ateca</modelo>
        <cv>150</cv>
        <combustible>Gasolina</combustible>
        <precio>23000</precio>
        <a単o>2025</a単o>
        <interesado>33329438t</interesado>
        <fecha_limite>31/12/2025</fecha_limite>
    </coche>

    <coche matricula="8280KWT">
        <marca>Volkswagen</marca>
        <modelo>Golf</modelo>
        <cv>120</cv>
        <combustible>Diesel</combustible>
        <precio>25000</precio>
        <a単o>2024</a単o>
        <interesado>33454538t</interesado>
        <fecha_limite>31/12/2025</fecha_limite>
    </coche>


</concesionario>
